# Custom alises regarding to directories for ZSH
# @https://zsh.sourceforge.io/Doc/Release/Shell-Grammar.html#Aliasing

os='undefined'
if [[ "$OSTYPE" == darwin* ]]; then
    os='mac'
elif [[ "$OSTYPE" == linux* ]]; then
    os='linux'
    alias open='xdg-open'
fi

alias -g ...='../..'
alias -g ....='../../..'
alias -g .....='../../../..'
alias -g ......='../../../../..'

alias -- -='cd -'
alias 1='cd -1'
alias 2='cd -2'
alias 3='cd -3'
alias 4='cd -4'
alias 5='cd -5'
alias 6='cd -6'
alias 7='cd -7'
alias 8='cd -8'
alias 9='cd -9'

alias md='mkdir -p'
alias rd='rmdir'

# directory management
alias opwd='open .'
alias ohome='open ~'

# rsync without files specified in .gitignore
alias rsyncgit="rsync -ahrvz --include='**.gitignore' --exclude='/.git' --filter=':- .gitignore' --delete-after"

# fasd
# alias automatically generated by zsh plugin in zshrc
if command -v fasd &> /dev/null
then
#     alias a='fasd -a' # file dir
#     alias s='fasd -si' # rank interactive
#     alias d='fasd -d' # dir
#     alias f='fasd -f' # file
#     alias sd='fasd -sid'
#     alias sf='fasd -sif'
#     alias z='fasd_cd -d'
#     alias zz='fasd_cd -d -i'
#     alias v='f -e vim'
#     alias o='a -e xdg-open'

    unalias sd 2>/dev/null
    unalias sf 2>/dev/null
fi

# exa
if command -v exa &> /dev/null
then
    alias ls='exa -F'
    alias la='exa -lahF'
    alias ll='exa -lhF'
    alias lag='exa -lahF --git'
    alias llg='exa -lhF --git'
    alias lt='exa -T'
    alias ltl='exa -T -L'

    alias lsrt='exa -lahF --sort'
    alias lsrtt='exa -lahF --sort=modified' # modified time by default: (modifed|accessed|changed)
    alias lsrts='exa -lahF --sort=size'
    alias lsrte='exa -lahF --sort=extension'
    alias lsrtn'exa -lahF --sort=name'

    alias l='exa -lahF'
else
    alias la='ls -al'
    alias ll='ls -l'
    if command -v tree &> /dev/null
    then
        alias lt='tree'
        alias ltl='tree -L'
    fi

    alias lsrt='ls -al --sort'
    alias lsrtt='ls -al --sort=time'
    alias lsrts='ls -al --sort=size'
    alias lsrte='ls -al --sort=extension'

    alias l='ls -al'
fi
