" Custom config for VIM

" basic setting
set fileencodings=utf8,euc-kr
set number
set ruler

" syntax highlighting
syntax on
filetype indent on
set showmatch

" indent
set backspace=indent,eol,start
set autoindent
set cindent
set smartindent

set ts=4
set shiftwidth=4
set expandtab " use space rather than tab
set smarttab

" search
set ignorecase
set smartcase
set hlsearch
set incsearch

" history
set history=10000
set undolevels=1000

" theme
set background=dark
colorscheme desert

" key mapping
let mapleader=','
let maplocalleader=','

nnoremap <leader>: :

nnoremap <silent> <leader>h :nohlsearch<CR>

source ~/.vim/plugins.vim

" Remember position of last edit and return on reopen
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

if has("unix")
  let s:uname = system("uname -s")
  if s:uname == "Darwin\n"
    " for MACOS where option right/left-arrows are remapped to ESC f/b
    " this allows user to use option right-arrow to move forward by word
    :map f w
  endif
endif
